name: CI

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    # name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Use Cached node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            node-modules-

      - name: Install Dependencies
        run: bun install

      - name: Publish Framework
        run: ./storage/framework/scripts/publish
        env:
          BUN_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish Dummy Libraries
        run: bun --filter='./storage/framework' run publish:dummy-libs
        env:
          BUN_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Publish VS Code Extension
        run: |
          cd storage/framework/defaults/ide/vscode
          bun install
          bunx --bun vsce publish
          cd ../../../../
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Create GitHub Release
        run: bunx changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Attach Binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            storage/framework/core/buddy/bin/buddy-linux-x64
            storage/framework/core/buddy/bin/buddy-linux-arm64
            storage/framework/core/buddy/bin/buddy-windows-x64.exe
            storage/framework/core/buddy/bin/buddy-darwin-x64
            storage/framework/core/buddy/bin/buddy-darwin-arm64
